include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    # Treat as warnings during migration
    unused_import: warning
    unused_local_variable: warning

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
    sort_pub_dependencies: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
