class EmojiCategory {
  final String title;
  final List<String> emojis;

  const EmojiCategory({
    required this.title,
    required this.emojis,
  });
}

class EmojiData {
  static const List<EmojiCategory> categories = [
    EmojiCategory(
      title: 'SMILEYS & PEOPLE',
      emojis: [
        '😀',
        '😃',
        '😄',
        '😁',
        '😆',
        '😅',
        '😂',
        '🤣',
        '😊',
        '😇',
        '🙂',
        '🙃',
        '😉',
        '😌',
        '😍',
        '🥰',
        '😘',
        '😗',
        '😙',
        '😚',
        '😋',
        '😛',
        '😝',
        '😜',
        '🤪',
        '🤨',
        '🧐',
        '🤓',
        '😎',
        '🤩',
        '🥳',
        '😏',
        '😒',
        '😞',
        '😔',
        '😟',
        '😕',
        '🙁',
        '☹️',
        '😣',
        '😖',
        '😫',
        '😩',
        '🥺',
        '😢',
        '😭',
        '😤',
        '😠',
        '😡',
        '🤬',
        '🤯',
        '😳',
        '🥵',
        '🥶',
        '😱',
        '😨',
        '😰',
        '😥',
        '😓',
        '🤗',
        '🤔',
        '🤭',
        '🤫',
        '🤥',
        '😶',
        '😐',
        '😑',
        '😬',
        '🙄',
        '😯',
        '😦',
        '😧',
        '😮',
        '😲',
        '🥱',
        '😴',
        '🤤',
        '😪',
        '😵',
        '🤐',
        '🥴',
        '🤢',
        '🤮',
        '🤧',
      ],
    ),
    EmojiCategory(
      title: 'ANIMALS & NATURE',
      emojis: [
        '🐶',
        '🐱',
        '🐭',
        '🐹',
        '🐰',
        '🦊',
        '🐻',
        '🐼',
        '🐨',
        '🐯',
        '🦁',
        '🐮',
        '🐷',
        '🐸',
        '🐵',
        '🙈',
        '🙉',
        '🙊',
        '🐔',
        '🐧',
        '🐦',
        '🐤',
        '🐣',
        '🐥',
        '🦆',
        '🦅',
        '🦉',
        '🦇',
        '🐺',
        '🐴',
        '🦄',
        '🐝',
        '🐛',
        '🦋',
        '🐌',
        '🐞',
        '🐜',
        '🦟',
        '🕷',
        '🕸',
        '🐢',
        '🐍',
        '🦎',
        '🦖',
        '🦕',
        '🐙',
        '🦑',
        '🦀',
        '🐠',
        '🐟',
        '🐬',
        '🐳',
        '🦈',
        '🐊',
        '🐅',
        '🐆',
        '🦓',
        '🦍',
        '🐘',
        '🦒',
        '🦘',
        '🐄',
        '🐎',
        '🐖',
        '🦌',
        '🐕',
        '🐈',
        '🕊',
        '🐇',
        '🐾',
        '🐉',
        '🌵',
        '🎄',
        '🌲',
        '🌳',
        '🌴',
        '🌱',
        '🌿',
        '☘️',
        '🍀',
        '🍁',
        '💐',
        '🌷',
        '🌹',
        '🥀',
        '🌺',
        '🌸',
        '🌼',
        '🌻',
        '🌞',
        '🌝',
        '🌛',
        '🌜',
        '🌚',
        '🌕',
        '🌑',
        '🌙',
        '🌎',
        '🌍',
        '🌏',
        '💫',
        '⭐️',
        '🌟',
        '✨',
        '⚡️',
        '💥',
        '🔥',
        '🌈',
        '☀️',
        '🌤',
        '⛅️',
        '☁️',
        '🌧',
        '❄️',
        '☃️',
        '⛄️',
        '💨',
        '💧',
        '💦',
        '☔️',
        '☂️',
        '🌊',
        '🐓',
        '🦃',
        '🔅',
        '🔆',
        '〽️',
        '🚸',
        '🔱',
        '⚜️',
      ],
    ),
    EmojiCategory(
      title: 'FOOD & DRINK',
      emojis: [
        '🍏',
        '🍎',
        '🍐',
        '🍊',
        '🍋',
        '🍌',
        '🍉',
        '🍇',
        '🍓',
        '🍒',
        '🥭',
        '🍍',
        '🥥',
        '🥝',
        '🍅',
        '🍆',
        '🥑',
        '🥦',
        '🥬',
        '🥒',
        '🌽',
        '🥕',
        '🥔',
        '🥐',
        '🥯',
        '🍞',
        '🥖',
        '🧀',
        '🥚',
        '🍳',
        '🥞',
        '🥓',
        '🥩',
        '🍗',
        '🍖',
        '🌭',
        '🍔',
        '🍟',
        '🍕',
        '🥪',
        '🌮',
        '🌯',
        '🥗',
        '🍝',
        '🍜',
        '🍲',
        '🍛',
        '🍣',
        '🍱',
        '🍤',
        '🍙',
        '🍚',
        '🍧',
        '🍨',
        '🍦',
        '🥧',
        '🧁',
        '🍰',
        '🎂',
        '🍮',
        '🍭',
        '🍬',
        '🍫',
        '🍿',
        '🍩',
        '🍪',
        '🥜',
        '🍯',
        '🥛',
        '🍼',
        '☕️',
        '🍵',
        '🥤',
        '🍺',
        '🍻',
        '🥂',
        '🍷',
        '🥃',
        '🍸',
        '🍹',
        '🍾',
        '🧊',
        '🥄',
        '🍴',
        '🍽',
        '🥣',
        '🥢',
        '🍑',
      ],
    ),
    EmojiCategory(
      title: 'ACTIVITIES & FASHION',
      emojis: [
        '⚽️',
        '🏀',
        '🏈',
        '⚾️',
        '🎾',
        '🏐',
        '🎱',
        '🏏',
        '⛳️',
        '🥊',
        '⛸',
        '🎿',
        '🏂',
        '🏋️‍♀️',
        '🏋️‍♂️',
        '🤸‍♀️',
        '🤸‍♂️',
        '🧘‍♀️',
        '🧘‍♂️',
        '🏄‍♀️',
        '🏄‍♂️',
        '🏊‍♀️',
        '🏊‍♂️',
        '🚴‍♀️',
        '🚴‍♂️',
        '🏆',
        '🥇',
        '🥈',
        '🥉',
        '🏅',
        '🎖',
        '🎟',
        '🎨',
        '🎬',
        '🎤',
        '🎧',
        '🎼',
        '🎹',
        '🥁',
        '🎷',
        '🎺',
        '🎸',
        '🎻',
        '🎲',
        '♟',
        '🎯',
        '🎳',
        '🎮',
        '🎰',
        '👗',
        '👠',
        '👜',
        '👕',
        '👖',
        '👔',
        '👙',
        '👚',
        '👛',
        '🎒',
        '👞',
        '👟',
        '👢',
        '👑',
        '👒',
        '🎩',
        '🎓',
        '🧢',
        '💄',
        '💍',
        '💼',
        '🎦',
      ],
    ),
    EmojiCategory(
      title: 'TRAVEL & PLACES',
      emojis: [
        '🚗',
        '🚕',
        '🚙',
        '🚌',
        '🏎',
        '🚓',
        '🚑',
        '🚒',
        '🚚',
        '🚛',
        '🛵',
        '🚲',
        '⛽️',
        '🚨',
        '🛑',
        '🚧',
        '⚓️',
        '⛵️',
        '🚢',
        '✈️',
        '🛫',
        '🛬',
        '🚁',
        '🚀',
        '🛸',
        '⌚️',
        '⏰',
        '⏱',
        '🎀',
        '🎁',
        '🎈',
        '🎊',
        '🎉',
        '🏙',
        '🌆',
        '🌇',
        '🌃',
        '🌉',
        '🗻',
        '🏠',
        '🏡',
        '🏢',
        '🏥',
        '🏦',
        '🏨',
        '🏫',
        '💒',
        '⛪️',
        '🕌',
      ],
    ),
    EmojiCategory(
      title: 'BODY PARTS',
      emojis: [
        '👋',
        '🤚',
        '🖐',
        '✋',
        '🖖',
        '👌',
        '🤌',
        '🤏',
        '✌️',
        '🤞',
        '🫰',
        '🤟',
        '🤘',
        '🤙',
        '👈',
        '👉',
        '👆',
        '🖕',
        '👇',
        '☝️',
        '👍',
        '👎',
        '✊',
        '👊',
        '🤛',
        '🤜',
        '👏',
        '🙌',
        '👐',
        '🤲',
        '🤝',
        '🙏',
        '✍️',
        '💅',
        '🤳',
        '💪',
        '🦵',
        '🦶',
        '👂',
        '👃',
        '🧠',
        '🦴',
        '👀',
        '👁',
        '👅',
        '👄',
        '🫀',
        '🫦',
      ],
    ),
    EmojiCategory(
      title: 'SYMBOLS & FLAGS',
      emojis: [
        '❤️',
        '🧡',
        '💛',
        '💚',
        '💙',
        '💜',
        '🖤',
        '🤍',
        '🤎',
        '💔',
        '❣️',
        '💕',
        '💞',
        '💓',
        '💗',
        '💖',
        '💘',
        '💝',
        '💟',
        '🆘',
        '❌',
        '⭕️',
        '🛑',
        '⛔️',
        '🚫',
        '💯',
        '💢',
        '♨️',
        '🔞',
        '❗️',
        '❕',
        '❓',
        '❔',
        '‼️',
        '⁉️',
        '⚠️',
        '♻️',
        '✅',
        '❎',
        '🌐',
        '🌀',
        '💤',
        '♿️',
        '🅿️',
        '🚹',
        '🚺',
        '🚻',
        '📶',
        'ℹ️',
        '🆗',
        '🆕',
        '🆓',
        '0️⃣',
        '1️⃣',
        '2️⃣',
        '3️⃣',
        '4️⃣',
        '5️⃣',
        '6️⃣',
        '7️⃣',
        '8️⃣',
        '9️⃣',
        '🔟',
        '#️⃣',
        '*️⃣',
        '♋️',
        '♌️',
      ],
    ),
  ];

  static const Map<String, String> keywords = {
    // SMILEYS & PEOPLE (Added generic terms: face, smiley, emotion)
    '😀': 'smile happy grin face smiley emotion',
    '😃': 'smile happy big face smiley emotion',
    '😄': 'smile happy laugh face smiley emotion',
    '😁': 'smile grin teeth happy face smiley emotion',
    '😆': 'laugh xd happy face smiley emotion',
    '😅': 'sweat smile nervous face smiley emotion',
    '😂': 'laugh cry tears lol face smiley emotion',
    '🤣': 'rofl laugh cry lol face smiley emotion',
    '😊': 'smile blush happy face smiley emotion',
    '😇': 'angel halo innocent good face smiley emotion',
    '🙂': 'smile slightly happy face smiley emotion',
    '🙃': 'upside down smile silly face smiley emotion',
    '😉': 'wink flirt face smiley emotion',
    '😌': 'relieved calm peace face smiley emotion',
    '😍': 'love heart eyes face smiley emotion',
    '🥰': 'love hearts affectionate face smiley emotion',
    '😘': 'kiss love heart face smiley emotion',
    '😗': 'kiss face smiley emotion',
    '😙': 'kiss smiling face smiley emotion',
    '😚': 'kiss closed eyes face smiley emotion',
    '😋': 'yummy delicious tongue hungry face smiley emotion',
    '😛': 'tongue out silly face smiley emotion',
    '😝': 'tongue squinting xd silly face smiley emotion',
    '😜': 'wink tongue silly joke face smiley emotion',
    '🤪': 'crazy silly goofy wacky face smiley emotion',
    '🤨': 'suspect suspicious eyebrow what face smiley emotion',
    '🧐': 'monocle fancy examine face smiley emotion',
    '🤓': 'nerd glasses smart geek face smiley emotion',
    '😎': 'cool sunglasses chill face smiley emotion',
    '🤩': 'star struck wow amazing face smiley emotion',
    '🥳': 'party celebrate birthday face smiley emotion',
    '😏': 'smirk flirt smug face smiley emotion',
    '😒': 'unamused annoyed meh face smiley emotion',
    '😞': 'disappointed sad face smiley emotion',
    '😔': 'pensive sad thoughtful face smiley emotion',
    '😟': 'worried sad anxious face smiley emotion',
    '😕': 'confused unsure face smiley emotion',
    '🙁': 'frown sad slightly face smiley emotion',
    '☹️': 'frown sad big face smiley emotion',
    '😣': 'persevere struggle pain face smiley emotion',
    '😖': 'confounded sad pain face smiley emotion',
    '😫': 'tired exhausted groan face smiley emotion',
    '😩': 'weary tired sigh face smiley emotion',
    '🥺': 'pleading puppy eyes beg sad face smiley emotion',
    '😢': 'cry tear sad face smiley emotion',
    '😭': 'cry sob sad tear bawl face smiley emotion',
    '😤': 'triumph mad angry huff face smiley emotion',
    '😠': 'angry mad grrr face smiley emotion',
    '😡': 'angry mad red pout face smiley emotion',
    '🤬': 'curse swear mad angry face smiley emotion',
    '🤯': 'mind blown explode wow shock face smiley emotion',
    '😳': 'flushed blush embarrassed shock face smiley emotion',
    '🥵': 'hot sweat summer face smiley emotion',
    '🥶': 'cold freezing winter face smiley emotion',
    '😱': 'scream scared horror face smiley emotion',
    '😨': 'fearful scared worried face smiley emotion',
    '😰': 'anxious sweat scared nervous face smiley emotion',
    '😥': 'sad relieved sweat face smiley emotion',
    '😓': 'sweat downcast tired face smiley emotion',
    '🤗': 'hug smiling hands friendly face smiley emotion hand gesture',
    '🤔': 'think hmm pondering face smiley emotion',
    '🤭': 'giggle hand over mouth oops face smiley emotion',
    '🤫': 'shh quiet secret face smiley emotion gesture',
    '🤥': 'liar pinocchio nose face smiley emotion',
    '😶': 'no mouth blank speechless face smiley emotion',
    '😐': 'neutral straight meh face smiley emotion',
    '😑': 'expressionless flat annoyed face smiley emotion',
    '😬': 'grimace yikes awkward face smiley emotion',
    '🙄': 'roll eyes whatever face smiley emotion',
    '😯': 'hushed surprise wow face smiley emotion',
    '😦': 'frowning open mouth sad shock face smiley emotion',
    '😧': 'anguished shocked sad face smiley emotion',
    '😮': 'open mouth surprise wow face smiley emotion',
    '😲': 'astonished shock wow face smiley emotion',
    '🥱': 'yawn tired sleep face smiley emotion',
    '😴': 'sleep zzz tired night face smiley emotion',
    '🤤': 'drool hungry sleep face smiley emotion',
    '😪': 'sleepy drop tear tired face smiley emotion',
    '😵': 'dizzy dead knocked out face smiley emotion',
    '🤐': 'zipper mouth secret shut face smiley emotion',
    '🥴': 'woozy drunk dizzy face smiley emotion',
    '🤢': 'nauseated sick green vomit face smiley emotion',
    '🤮': 'vomit throw up sick puke face smiley emotion',
    '🤧': 'sneeze sick cold bless you face smiley emotion',

    // ANIMALS & NATURE (Added generic terms: animal, nature, pet, bird, bug, water, space)
    '🐶': 'dog puppy pet animal nature',
    '🐱': 'cat kitten pet animal nature',
    '🐭': 'mouse rat pet animal nature',
    '🐹': 'hamster pet animal nature',
    '🐰': 'rabbit bunny pet animal nature',
    '🦊': 'fox wild animal nature',
    '🐻': 'bear grizzly wild animal nature',
    '🐼': 'panda bear wild animal nature',
    '🐨': 'koala bear wild animal nature australia',
    '🐯': 'tiger big cat wild animal nature',
    '🦁': 'lion king cat wild animal nature',
    '🐮': 'cow farm moo animal nature',
    '🐷': 'pig farm oink animal nature',
    '🐸': 'frog toad amphibian animal nature',
    '🐵': 'monkey face wild animal nature',
    '🙈': 'see no evil monkey blind animal gesture',
    '🙉': 'hear no evil monkey deaf animal gesture',
    '🙊': 'speak no evil monkey mute animal gesture',
    '🐔': 'chicken bird farm animal nature',
    '🐧': 'penguin bird cold animal nature',
    '🐦': 'bird fly animal nature',
    '🐤': 'baby chick bird animal nature',
    '🐣': 'hatching chick bird egg animal nature',
    '🐥': 'chick front baby bird animal nature',
    '🦆': 'duck bird quack animal nature water',
    '🦅': 'eagle bird fly wild animal nature usa',
    '🦉': 'owl bird night wild animal nature',
    '🦇': 'bat fly night scary wild animal nature',
    '🐺': 'wolf howl dog wild animal nature',
    '🐴': 'horse farm ride animal nature',
    '🦄': 'unicorn magic horse animal nature fantasy',
    '🐝': 'bee bug insect fly honey animal nature',
    '🐛': 'bug caterpillar insect animal nature',
    '🦋': 'butterfly bug insect beautiful animal nature',
    '🐌': 'snail bug slow insect animal nature',
    '🐞': 'ladybug bug insect animal nature',
    '🐜': 'ant bug insect animal nature',
    '🦟': 'mosquito bug insect bite animal nature',
    '🕷': 'spider bug insect scary animal nature',
    '🕸': 'spider web bug trap nature',
    '🐢': 'turtle slow reptile animal nature sea',
    '🐍': 'snake slither reptile animal nature',
    '🦎': 'lizard reptile wild animal nature',
    '🦖': 't-rex dinosaur extinct animal nature',
    '🦕': 'sauropod dinosaur brontosaurus animal nature',
    '🐙': 'octopus sea ocean water animal nature',
    '🦑': 'squid sea ocean water animal nature',
    '🦀': 'crab sea ocean beach water animal nature',
    '🐠': 'tropical fish sea ocean pet water animal nature',
    '🐟': 'fish sea ocean water animal nature',
    '🐬': 'dolphin sea ocean flip water animal nature',
    '🐳': 'whale spouting sea ocean water animal nature',
    '🦈': 'shark sea ocean danger water animal nature',
    '🐊': 'crocodile alligator reptile water animal nature',
    '🐅': 'tiger wild cat animal nature',
    '🐆': 'leopard fast wild cat animal nature',
    '🦓': 'zebra horse stripes wild animal nature',
    '🦍': 'gorilla ape monkey wild animal nature',
    '🐘': 'elephant trunk big wild animal nature',
    '🦒': 'giraffe tall neck wild animal nature',
    '🦘': 'kangaroo jump wild animal nature australia',
    '🐄': 'cow farm milk animal nature',
    '🐎': 'horse ride race farm animal nature',
    '🐖': 'pig farm bacon animal nature',
    '🦌': 'deer buck horn wild animal nature',
    '🐕': 'dog pet walk animal nature',
    '🐈': 'cat pet walk animal nature',
    '🕊': 'dove bird peace fly animal nature',
    '🐇': 'rabbit bunny pet animal nature',
    '🐾': 'paw prints dog cat pet animal track',
    '🐉': 'dragon mythical magic animal nature',
    '🌵': 'cactus plant desert prickly nature',
    '🎄': 'christmas tree holiday plant nature',
    '🌲': 'evergreen tree pine plant nature forest',
    '🌳': 'tree plant wood nature forest',
    '🌴': 'palm tree beach tropical plant nature',
    '🌱': 'seedling plant grow leaf nature',
    '🌿': 'herb plant leaf nature',
    '☘️': 'shamrock clover green plant nature',
    '🍀': 'four leaf clover lucky plant nature',
    '🍁': 'maple leaf autumn fall plant nature',
    '💐': 'bouquet flowers gift romance plant nature',
    '🌷': 'tulip flower spring plant nature',
    '🌹': 'rose flower red romance love plant nature',
    '🥀': 'wilted flower dead sad rose plant nature',
    '🌺': 'hibiscus flower tropical hawaii plant nature',
    '🌸': 'cherry blossom pink spring flower plant nature',
    '🌼': 'blossom flower yellow spring plant nature',
    '🌻': 'sunflower yellow plant nature',
    '🌞': 'sun face happy summer sky nature',
    '🌝': 'full moon face night sky space nature',
    '🌛': 'first quarter moon face night sky space',
    '🌜': 'last quarter moon face night sky space',
    '🌚': 'new moon face dark night sky space',
    '🌕': 'full moon yellow night sky space nature',
    '🌑': 'new moon dark night sky space nature',
    '🌙': 'crescent moon night sleep sky space nature',
    '🌎': 'earth americas globe world planet space nature',
    '🌍': 'earth africa globe world planet space nature',
    '🌏': 'earth asia globe world planet space nature',
    '💫': 'dizzy star magic spark space',
    '⭐️': 'star gold shape sky space nature',
    '🌟': 'glowing star magic shine sky space nature',
    '✨': 'sparkles stars magic glitter',
    '⚡️': 'high voltage lightning electric storm nature',
    '💥': 'collision boom explode crash',
    '🔥': 'fire hot burn flame lit nature',
    '🌈': 'rainbow colors weather pride nature sky',
    '☀️': 'sun warm weather bright sky nature',
    '🌤': 'sun behind small cloud weather sky nature',
    '⛅️': 'sun behind cloud weather sky nature',
    '☁️': 'cloud weather grey sky nature',
    '🌧': 'cloud with rain weather wet sky nature',
    '❄️': 'snowflake winter cold snow weather nature',
    '☃️': 'snowman snow winter cold weather nature',
    '⛄️': 'snowman without snow cold weather nature',
    '💨': 'dashing away wind blow fast air nature',
    '💧': 'droplet water tear wet nature',
    '💦': 'sweat water drops wet splash liquid nature mature',
    '☔️': 'umbrella with rain drops weather wet',
    '☂️': 'umbrella rain weather dry',
    '🌊': 'water wave sea ocean surf nature liquid',
    '🐓': 'rooster chicken farm bird animal nature',
    '🦃': 'turkey bird thanksgiving farm animal nature',
    '🔅': 'dim button brightness low symbol',
    '🔆': 'bright button brightness high symbol',
    '〽️': 'part alternation mark music symbol',
    '🚸': 'children crossing sign warning symbol',
    '🔱': 'trident emblem pitchfork spear symbol',
    '⚜️': 'fleur de lis scout french symbol',

    // FOOD & DRINK (Added generic terms: food, eat, drink, meal, fruit, veg, sweet)
    '🍏': 'green apple fruit food eat',
    '🍎': 'red apple fruit food eat healthy',
    '🍐': 'pear green fruit food eat',
    '🍊': 'tangerine orange fruit food eat',
    '🍋': 'lemon yellow sour fruit food eat',
    '🍌': 'banana yellow monkey fruit food eat',
    '🍉': 'watermelon summer green red fruit food eat',
    '🍇': 'grapes purple wine fruit food eat',
    '🍓': 'strawberry red berry fruit food eat sweet',
    '🍒': 'cherries red fruit food eat sweet',
    '🥭': 'mango tropical yellow fruit food eat',
    '🍍': 'pineapple tropical yellow fruit food eat',
    '🥥': 'coconut tropical brown white fruit food eat',
    '🥝': 'kiwi green brown fruit food eat',
    '🍅': 'tomato red veg vegetable fruit food eat',
    '🍆': 'eggplant purple vegetable veg food eat mature',
    '🥑': 'avocado green healthy vegetable veg fruit food eat',
    '🥦': 'broccoli green vegetable veg food eat healthy',
    '🥬': 'leafy green lettuce cabbage vegetable veg food eat',
    '🥒': 'cucumber green pickle vegetable veg food eat',
    '🌽': 'ear of corn yellow vegetable veg food eat',
    '🥕': 'carrot orange rabbit vegetable veg food eat',
    '🥔': 'potato brown root vegetable veg food eat',
    '🥐': 'croissant bread pastry french food eat breakfast',
    '🥯': 'bagel bread bakery round food eat breakfast',
    '🍞': 'bread loaf bakery carb food eat',
    '🥖': 'baguette bread bakery french food eat',
    '🧀': 'cheese yellow dairy mouse food eat',
    '🥚': 'egg white poultry breakfast food eat',
    '🍳': 'cooking fry pan egg breakfast food eat',
    '🥞': 'pancakes syrup stack breakfast food eat sweet',
    '🥓': 'bacon meat pork breakfast food eat',
    '🥩': 'cut of meat steak beef food eat meal',
    '🍗': 'poultry leg chicken turkey meat food eat meal',
    '🍖': 'meat on bone beef pork food eat meal',
    '🌭': 'hot dog sausage bread fast food eat meal',
    '🍔': 'hamburger burger meat fast food eat meal',
    '🍟': 'french fries potato fast food eat meal',
    '🍕': 'pizza slice cheese fast food eat meal',
    '🥪': 'sandwich bread lunch food eat meal',
    '🌮': 'taco mexican shell food eat meal',
    '🌯': 'burrito wrap mexican food eat meal',
    '🥗': 'green salad bowl healthy veg vegetable food eat meal',
    '🍝': 'spaghetti pasta noodles italian food eat meal',
    '🍜': 'steaming bowl ramen soup noodles food eat meal',
    '🍲': 'pot stew soup food eat meal',
    '🍛': 'curry rice spicy food eat meal',
    '🍣': 'sushi fish rice japanese food eat meal',
    '🍱': 'bento box lunch japanese food eat meal',
    '🍤': 'fried shrimp tempura seafood food eat',
    '🍙': 'rice ball onigiri japanese food eat',
    '🍚': 'cooked white rice bowl food eat',
    '🍧': 'shaved ice dessert sweet cold food eat',
    '🍨': 'ice cream dessert sweet cold bowl food eat',
    '🍦': 'ice cream cone dessert sweet cold food eat',
    '🥧': 'pie dessert sweet baked food eat',
    '🧁': 'cupcake dessert cake sweet food eat',
    '🍰': 'shortcake dessert slice cake sweet food eat',
    '🎂': 'birthday cake dessert party sweet food eat',
    '🍮': 'custard flan dessert sweet food eat',
    '🍭': 'lollipop candy sugar sweet food eat',
    '🍬': 'candy wrapper sugar sweet food eat',
    '🍫': 'chocolate bar candy sweet food eat',
    '🍿': 'popcorn movie snack corn food eat',
    '🍩': 'doughnut donut pastry cake sweet food eat',
    '🍪': 'cookie chocolate chip dessert sweet food eat',
    '🥜': 'peanuts nut shell allergy food eat',
    '🍯': 'honey pot bee sweet food eat',
    '🥛': 'glass of milk cow dairy drink beverage',
    '🍼': 'baby bottle milk drink beverage',
    '☕️': 'hot coffee tea cup cafe drink beverage',
    '🍵': 'teacup matcha green drink beverage',
    '🥤': 'cup with straw soda water drink beverage',
    '🍺': 'beer mug alcohol bar drink beverage',
    '🍻': 'clinking beer mugs party alcohol drink beverage',
    '🥂': 'clinking glasses cheers champagne alcohol drink beverage',
    '🍷': 'wine glass red alcohol drink beverage',
    '🥃': 'tumbler glass whiskey alcohol drink beverage',
    '🍸': 'cocktail glass martini alcohol drink beverage',
    '🍹': 'tropical fruit cocktail alcohol drink beverage',
    '🍾': 'bottle popping cork champagne party alcohol drink beverage',
    '🧊': 'ice cube cold freeze water drink beverage',
    '🥄': 'spoon silverware soup eat utensil',
    '🍴': 'fork and knife silverware dinner eat utensil',
    '🍽': 'fork and knife with plate silverware dinner eat meal',
    '🥣': 'bowl with spoon soup cereal eat meal',
    '🥢': 'chopsticks asian tool eat utensil',
    '🍑': 'peach fruit butt mature food eat',

    // ACTIVITIES & FASHION (Added generic terms: sport, play, game, clothing, fashion, wear)
    '⚽️': 'soccer football ball sport play game',
    '🏀': 'basketball ball hoop sport play game',
    '🏈': 'american football ball sport play game',
    '⚾️': 'baseball ball bat sport play game',
    '🎾': 'tennis ball racket sport play game',
    '🏐': 'volleyball ball net sport play game',
    '🎱': 'pool 8 ball billiards magic sport play game',
    '🏏': 'cricket bat ball sport play game',
    '⛳️': 'flag in hole golf sport play game',
    '🥊': 'boxing glove fight punch sport play game',
    '⛸': 'ice skate winter cold sport play activity',
    '🎿': 'skis winter snow cold sport play activity',
    '🏂': 'snowboarder winter snow sport play activity',
    '🏋️‍♀️': 'woman lifting weights gym workout sport body activity',
    '🏋️‍♂️': 'man lifting weights gym workout sport body activity',
    '🤸‍♀️': 'woman cartwheeling gymnastics sport body activity',
    '🤸‍♂️': 'man cartwheeling gymnastics sport body activity',
    '🧘‍♀️': 'woman lotus yoga meditate zen body activity',
    '🧘‍♂️': 'man lotus yoga meditate zen body activity',
    '🏄‍♀️': 'woman surfing wave ocean water board sport activity',
    '🏄‍♂️': 'man surfing wave ocean water board sport activity',
    '🏊‍♀️': 'woman swimming pool water sport body activity',
    '🏊‍♂️': 'man swimming pool water sport body activity',
    '🚴‍♀️': 'woman biking bicycle ride sport activity',
    '🚴‍♂️': 'man biking bicycle ride sport activity',
    '🏆': 'trophy win award prize gold sport game',
    '🥇': '1st place medal gold win award sport',
    '🥈': '2nd place medal silver award sport',
    '🥉': '3rd place medal bronze award sport',
    '🏅': 'medal award win ribbon sport',
    '🎖': 'military medal award army star',
    '🎟': 'admission tickets event movie pass',
    '🎨': 'artist palette paint draw art activity',
    '🎬': 'clapper board movie film director activity',
    '🎤': 'microphone sing music karaoke voice activity',
    '🎧': 'headphone listen music audio activity',
    '🎼': 'musical score note clef song music activity',
    '🎹': 'musical keyboard piano instrument play music activity',
    '🥁': 'drum instrument band beat bang music activity',
    '🎷': 'saxophone instrument jazz music activity',
    '🎺': 'trumpet instrument brass band horn music activity',
    '🎸': 'guitar instrument rock band music activity',
    '🎻': 'violin instrument orchestra string music activity',
    '🎲': 'die dice casino roll luck play game',
    '♟': 'chess pawn board piece play game',
    '🎯': 'direct hit bullseye dart target aim play game',
    '🎳': 'bowling strike ball pin sport play game',
    '🎮': 'video controller console ps xbox play game',
    '🎰': 'slot machine casino gamble luck 777 play game',
    '👗': 'dress woman apparel clothing fashion wear',
    '👠': 'high heeled shoe woman stiletto clothing fashion wear',
    '👜': 'handbag purse bag accessory clothing fashion wear',
    '👕': 't-shirt shirt top apparel clothing fashion wear',
    '👖': 'jeans pants denim apparel clothing fashion wear',
    '👔': 'necktie shirt suit business apparel clothing fashion wear',
    '👙': 'bikini swimsuit swim beach clothing fashion wear',
    '👚': 'woman clothes shirt top pink clothing fashion wear',
    '👛': 'purse pouch bag coin wallet clothing fashion wear',
    '🎒': 'backpack school bag pack accessory fashion',
    '👞': 'man shoe brown leather clothing fashion wear',
    '👟': 'running shoe sneaker sport clothing fashion wear',
    '👢': 'woman boot shoe apparel clothing fashion wear',
    '👑': 'crown king queen prince royal fashion accessory',
    '👒': 'woman hat summer sun clothing fashion wear',
    '🎩': 'top hat magic fancy gentleman clothing fashion wear',
    '🎓': 'graduation cap school college university hat fashion wear',
    '🧢': 'billed cap baseball hat clothing fashion wear',
    '💄': 'lipstick makeup beauty cosmetics fashion body',
    '💍': 'ring diamond marry engagement jewelry fashion wear',
    '💼': 'briefcase business bag work office accessory fashion',
    '🎦': 'cinema movie theater film sign',

    // TRAVEL & PLACES (Added generic terms: vehicle, travel, transport, building, place)
    '🚗': 'automobile car drive vehicle travel transport',
    '🚕': 'taxi cab yellow vehicle travel transport',
    '🚙': 'sport utility suv jeep car vehicle travel transport',
    '🚌': 'bus school transit vehicle travel transport',
    '🏎': 'racing car fast sports vehicle travel transport',
    '🚓': 'police car cop siren light vehicle travel transport',
    '🚑': 'ambulance hospital medical siren vehicle travel transport',
    '🚒': 'fire engine truck siren emergency vehicle travel transport',
    '🚚': 'delivery truck shipping move vehicle travel transport',
    '🚛': 'articulated lorry semi truck vehicle travel transport',
    '🛵': 'motor scooter motorcycle bike vehicle travel transport',
    '🚲': 'bicycle bike ride cycle vehicle travel transport',
    '⛽️': 'fuel pump gas station petrol car place',
    '🚨': 'police car light siren emergency warning',
    '🚧': 'construction sign hazard warning build',
    '⚓️': 'anchor ship boat ocean sea vehicle transport',
    '⛵️': 'sailboat water ship ocean sea vehicle travel transport',
    '🚢': 'ship boat water ocean cruise vehicle travel transport',
    '✈️': 'airplane flight fly sky vehicle travel transport',
    '🛫': 'airplane departure fly takeoff vehicle travel transport',
    '🛬': 'airplane arrival fly land vehicle travel transport',
    '🚁': 'helicopter flight fly chopper vehicle travel transport',
    '🚀': 'rocket ship space fly blast launch vehicle travel transport',
    '🛸': 'flying saucer ufo alien space ship vehicle travel transport',
    '⌚️': 'watch time clock wrist apple wear accessory',
    '⏰': 'alarm clock time wake ring',
    '⏱': 'stopwatch time race clock',
    '🎀': 'ribbon pink bow tie cute accessory',
    '🎁': 'wrapped gift present box surprise birthday',
    '🎈': 'balloon red party birthday celebrate',
    '🎊': 'confetti ball party celebrate birthday',
    '🎉': 'party popper celebrate birthday tada',
    '🏙': 'cityscape buildings sky town urban place building',
    '🌆': 'cityscape at dusk sunset town place building',
    '🌇': 'sunset sun down evening sky dusk place',
    '🌃': 'night with stars city dark sky place',
    '🌉': 'bridge at night water lights place building',
    '🗻': 'mount fuji mountain japan snow volcano place nature',
    '🏠': 'house home door living place building',
    '🏡': 'house with garden home yard tree place building',
    '🏢': 'office business city work place building',
    '🏥': 'hospital medical cross health place building',
    '🏦': 'bank money finance place building',
    '🏨': 'hotel sleep stay travel place building',
    '🏫': 'school learn education study place building',
    '💒': 'wedding marriage church love place building',
    '⛪️': 'church cross religion pray place building',
    '🕌': 'mosque islam religion pray muslim place building',

    // BODY PARTS (Added generic terms: body, part, anatomy, hand, gesture)
    '👋': 'waving wave hello hi bye hand gesture body part',
    '🤚': 'raised back of stop high five hand gesture body part',
    '🖐': 'fingers splayed stop five hand gesture body part',
    '✋': 'raised stop high five hand gesture body part',
    '🖖': 'vulcan salute spock star trek prosper hand gesture body part',
    '👌': 'ok perfect good yes hand gesture body part',
    '🤌': 'pinched fingers italian chef kiss hand gesture body part',
    '🤏': 'pinching small tiny little bit hand gesture body part',
    '✌️': 'victory peace two v sign hand gesture body part',
    '🤞': 'crossed fingers luck hope wish hand gesture body part',
    '🫰': 'crossed heart love kpop hand gesture body part',
    '🤟': 'love you rock deaf sign hand gesture body part',
    '🤘': 'sign of the horns rock heavy metal hand gesture body part',
    '🤙': 'call me shaka surf phone hand gesture body part',
    '👈': 'backhand index pointing left direction hand gesture body part',
    '👉': 'backhand index pointing right direction hand gesture body part',
    '👆': 'backhand index pointing up direction hand gesture body part',
    '🖕': 'middle finger flip off rude hand gesture body part',
    '👇': 'backhand index pointing down direction hand gesture body part',
    '☝️': 'index pointing up direction one hand gesture body part',
    '👍': 'thumbs up like good yes approve hand gesture body part',
    '👎': 'thumbs down dislike bad no disapprove hand gesture body part',
    '✊': 'raised fist punch power rock hand gesture body part',
    '👊': 'oncoming fist punch bump bro hand gesture body part',
    '🤛': 'left facing fist punch bump hand gesture body part',
    '🤜': 'right facing fist punch bump hand gesture body part',
    '👏': 'clapping clap applaud praise bravo hand gesture body part',
    '🙌': 'raising celebrate hooray yay praise hand gesture body part',
    '👐': 'open hug palm hand gesture body part',
    '🤲': 'palms up together pray beg hand gesture body part',
    '🤝': 'handshake deal agree greet meeting hand gesture body part',
    '🙏': 'folded pray please thanks namaste hand gesture body part',
    '✍️': 'writing write pen pencil sign hand gesture body part',
    '💅': 'nail polish beauty manicure sassy fashion hand gesture body part',
    '🤳': 'selfie phone camera photo picture hand gesture body part',
    '💪': 'flexed biceps muscle strong arm gym body part anatomy',
    '🦵': 'leg limb walk run kick body part anatomy',
    '🦶': 'foot toe walk kick body part anatomy',
    '👂': 'ear hear listen sound body part anatomy',
    '👃': 'nose smell sniff scent body part anatomy',
    '🧠': 'brain smart think mind head body part anatomy',
    '🦴': 'bone skeleton dog body part anatomy',
    '👀': 'eyes look watch see stare peek body part anatomy',
    '👁': 'eye look watch see vision body part anatomy',
    '👅': 'tongue lick taste mouth silly body part anatomy',
    '👄': 'mouth lips kiss speak talk body part anatomy',
    '🫀': 'anatomical heart real biology beat body part anatomy',
    '🫦': 'biting lip sexy mature flirt mouth body part anatomy',

    // SYMBOLS & FLAGS (Added generic terms: heart, shape, symbol)
    '❤️': 'red love like passion emotion heart shape symbol',
    '🧡': 'orange love like color emotion heart shape symbol',
    '💛': 'yellow love like color friendship emotion heart shape symbol',
    '💚': 'green love like color nature emotion heart shape symbol',
    '💙': 'blue love like color sky water emotion heart shape symbol',
    '💜': 'purple love like color bts emotion heart shape symbol',
    '🖤': 'black love like dark goth emo emotion heart shape symbol',
    '🤍': 'white love like pure clean emotion heart shape symbol',
    '🤎': 'brown love like color chocolate emotion heart shape symbol',
    '💔': 'broken sad breakup rip tear emotion heart shape symbol',
    '❣️': 'heavy exclamation mark love punctuation emotion heart shape symbol',
    '💕': 'two love like float pair emotion heart shape symbol',
    '💞': 'revolving love like spin together emotion heart shape symbol',
    '💓': 'beating love beat throb flutter emotion heart shape symbol',
    '💗': 'growing love pink swell pulse emotion heart shape symbol',
    '💖': 'sparkling love magic star shine emotion heart shape symbol',
    '💘': 'with arrow love cupids hit strike emotion heart shape symbol',
    '💝': 'with ribbon love box gift present emotion heart shape symbol',
    '💟': 'decoration love purple box pattern emotion heart shape symbol',
    '🆘': 'sos button help emergency save red symbol',
    '❌': 'cross mark x no wrong fail stop symbol',
    '⭕️': 'hollow red circle o correct yes tick symbol',
    '🛑': 'stop sign red halt octagon warning symbol',
    '⛔️': 'no entry sign red stop block forbidden symbol',
    '🚫': 'prohibited sign no stop ban block symbol',
    '💯': 'hundred points 100 perfect exam score keep it real symbol',
    '💢': 'anger mad veins red pop symbol',
    '♨️': 'hot springs steam heat warm bath symbol',
    '🔞': 'no one under eighteen 18 age mature adult limit symbol',
    '❗️': 'exclamation mark point red alert warn symbol',
    '❕': 'white exclamation mark point alert warn symbol',
    '❓': 'question mark red query what ask symbol',
    '❔': 'white question mark query what ask symbol',
    '‼️': 'double exclamation mark red alert warn danger symbol',
    '⁉️': 'exclamation question mark interrobang what red alert symbol',
    '⚠️': 'warning sign yellow hazard caution alert triangle symbol',
    '♻️': 'recycling green reuse environment eco symbol',
    '✅': 'check mark button green tick yes ok correct done symbol',
    '❎': 'cross mark button green x no cancel symbol',
    '🌐': 'globe meridians earth internet web world wide symbol',
    '🌀': 'cyclone swirl spin dizzy blue storm symbol',
    '💤': 'zzz sleep tired snore bore symbol',
    '♿️': 'wheelchair accessible handicap disability blue symbol',
    '🅿️': 'p button parking blue car park symbol',
    '🚹': 'men room male man bathroom washroom symbol',
    '🚺': 'women room female woman bathroom washroom symbol',
    '🚻': 'restroom wc bathroom washroom toilet sign symbol',
    '📶': 'antenna bars signal wifi phone connection internet symbol',
    'ℹ️': 'information i help blue details info symbol',
    '🆗': 'ok button blue okay good yes done symbol',
    '🆕': 'new button blue fresh recent update symbol',
    '🆓': 'free button blue cost zero price nothing symbol',
    '0️⃣': 'keycap digit zero 0 number blue symbol',
    '1️⃣': 'keycap digit one 1 number blue first symbol',
    '2️⃣': 'keycap digit two 2 number blue second symbol',
    '3️⃣': 'keycap digit three 3 number blue third symbol',
    '4️⃣': 'keycap digit four 4 number blue symbol',
    '5️⃣': 'keycap digit five 5 number blue symbol',
    '6️⃣': 'keycap digit six 6 number blue symbol',
    '7️⃣': 'keycap digit seven 7 number blue luck symbol',
    '8️⃣': 'keycap digit eight 8 number blue symbol',
    '9️⃣': 'keycap digit nine 9 number blue symbol',
    '🔟': 'keycap ten 10 number blue perfect symbol',
    '#️⃣': 'hash key hashtag pound number sign blue symbol',
    '*️⃣': 'asterisk key star blue multiply symbol',
    '♋️': 'cancer zodiac crab astrology purple symbol',
    '♌️': 'leo zodiac lion astrology purple symbol',
  };
}
